version: '3.8'
services:
  api:
    build: .
    image: flaskapp
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: book_ratings.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://ratings_user:password@localhost/ratings
    volumes:
      - ".:/app"
    networks:
      pgflaskapp:
    depends_on:
      - "db"
    command: [ "./entrypoint.sh"]
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: rating_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rating
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      pgflaskapp:
        aliases:
          - 'postgres'
volumes:
  postgres-db:
networks:
  pgflaskapp:
    driver: bridge
