"""empty message

Revision ID: 383014a2312a
Revises: 
Create Date: 2022-01-07 12:52:38.629221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383014a2312a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('only_one_book_rating_per_user', 'book_ratings', ['book_id', 'email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('only_one_book_rating_per_user', table_name='book_ratings')
    op.drop_table('book_ratings')
    # ### end Alembic commands ###
